apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: simple-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: nexus-svc.nexus.svc.cluster.local:8082/truelykh/frontend:1
          ports:
            - containerPort: 80
